## 정규표현식

In [181]:
import re
#re.search(정규표현식, 찾을 문자열 대상)
m = re.search(r"abc", "123ab cdef") #띄어쓰기를 기준으로 찾음
print(m)

print(re.search(r"abc","abcabc"))   # 최초로 매칭되는 패턴만 반환

m = re.search(r"\d\d\d\w", "d112119")
print(m)

print(re.search(r"\D","\n"))

m = re.search(r"..\w\w", "abcd")
print(m)

# \d = 모든 숫자 중에 하나[0-9], \w = 모든 문자, 숫자 중에 하나[0-9A-Za-z], . = 특수문자까자 포함한 \n을 제외한 것 중에 하나
# \D = 숫자가 아닌 문자 [^0-9] => 특수문자 포함,공백 포함 \W = 모든 문자, 숫자가 아닌것, 특수문자[^0-9A-Za-z] / 공백 포함
# \s = 공백문자(탭,띄어쓰기, 엔터) # \S = 공백이 아닌 문자

# \. [.] [+] [*] \\ [?] 은 문자 그대로 작동

None
<_sre.SRE_Match object; span=(0, 3), match='abc'>
<_sre.SRE_Match object; span=(1, 5), match='1121'>
<_sre.SRE_Match object; span=(0, 1), match='\n'>
<_sre.SRE_Match object; span=(0, 4), match='abcd'>


In [200]:
print(re.search(r"[0-9]","2345")) #[] 는 하나의 문자 자체에 대응되는 것임!


<_sre.SRE_Match object; span=(0, 1), match='2'>


In [189]:
print(re.search("[\d-]+-[\d]+","980203-235353 haha 980204-124 hehehe"))
print(re.findall("[\d-]+-[\d]+","980203-235353 haha 980204-124 hehehe"))
print(re.match("[\d-]+-[\d]+","e980203-235353 haha 980204-124 hehehe"))
print(re.match("[\d-]+-[\d]+","980203-235353 haha 980204-124 hehehe"))
com = re.compile("[\d-]+-[\d]+")
print(com.findall("980203-235353 haha 980204-124 hehehe"))
print(com.match("980203-235353 haha 980204-124 hehehe"))
print(com.search("980203-235353 haha 980204-124 hehehe"))

<_sre.SRE_Match object; span=(0, 13), match='980203-235353'>
['980203-235353', '980204-124']
None
<_sre.SRE_Match object; span=(0, 13), match='980203-235353'>
['980203-235353', '980204-124']
<_sre.SRE_Match object; span=(0, 13), match='980203-235353'>
<_sre.SRE_Match object; span=(0, 13), match='980203-235353'>


### $이 맨 마지막에 쓰이면 무조건 맨 뒤에서부터 검색, 맨 뒤의 위치가 아닐 땐 그냥 문자열
### ^이 맨앞에  쓰이면 무조건 앞에서부터, 맨앞의 위치가 아닐 땐 그냥 문자열


### 반복  
- "+" = 한번 이상 반복 될때  
re.search("ca+","c") => None  
- "*" = 0번 이상 반복 될때  
re.search("ca*","c") => c  

- ? = 앞문자가 있어도 되고 없어도 된다. 즉 0번이나 1번 반복될 때  
re.search("ca","c") = > c  

In [191]:
print(re.search(r"b[\w]+a","cabana"))

print(re.search(r"abcd+end","abcendenddddend")) # 1번 이상의 반복
print(re.search(r"^b\w+a","cabana")) #무조건 맨앞에서 부터 일치하지 않으면 None 반환
print(re.search(r"^b\w+a","baaafdfa")) 
print(re.search(r"d+dfd","dddddfd"))
# + 는 앞에꺼와 동일한 것이라는 의미, 몇개든 상관없음. 동일하기만 하면 됨. 뒤에꼐 나오는 맨 마지막까지 까지 해줌
# Maximum 하게 작동

print(re.search(r"b\w+a$", "cabana"))

<_sre.SRE_Match object; span=(2, 6), match='bana'>
None
None
<_sre.SRE_Match object; span=(0, 8), match='baaafdfa'>
<_sre.SRE_Match object; span=(0, 7), match='dddddfd'>
<_sre.SRE_Match object; span=(2, 6), match='bana'>


In [190]:
print(re.search(r"b\w*a","cabana"))

print(re.search(r"abcd*e","abcedededdd")) # 0번 이상의 반복
print(re.search(r"^b\w*a","cabana")) #무조건 맨앞에서 부터 일치하지 않으면 None 반환
print(re.search(r"^b\w*a","baaafdfa")) 
print(re.search(r"d*dfd","dddddfd"))
# * 는 앞에꺼와 동일한 것이라는 의미, 몇개든 상관없음. 동일하기만 하면 됨. 뒤에꼐 나오는 맨 마지막까지 까지 해줌
# Maximum 하게 작동

print(re.search(r"b\w*a$", "cabana"))

<_sre.SRE_Match object; span=(2, 6), match='bana'>
<_sre.SRE_Match object; span=(0, 4), match='abce'>
None
<_sre.SRE_Match object; span=(0, 8), match='baaafdfa'>
<_sre.SRE_Match object; span=(0, 7), match='dddddfd'>
<_sre.SRE_Match object; span=(2, 6), match='bana'>


In [192]:
print(re.search(r"b\w?a","cabana"))

print(re.search(r"abcd?e","abcdddedededdd")) # 0번이나 1번 반복에 대해서 가능.
print(re.search(r"^b\w?a","cabana")) #무조건 맨앞에서 부터 일치하지 않으면 None 반환
print(re.search(r"^b\w?a","baaafdfa")) 
print(re.search(r"d?dfd","dddddfd"))
# ? 는 앞에꺼와 동일한 것이라는 의미, 몇개든 상관없음. 동일하기만 하면 됨. 뒤에꼐 나오는 맨 마지막까지 까지 해줌
# Maximum 하게 작동

print(re.search(r"b\w?a$", "cabana"))

<_sre.SRE_Match object; span=(2, 4), match='ba'>
None
None
<_sre.SRE_Match object; span=(0, 3), match='baa'>
<_sre.SRE_Match object; span=(3, 7), match='ddfd'>
None


### Grouping

In [28]:
m = re.search(r"(\w+)@(.+)", "test@gmail.com")
print(m.group(1))
print(m.group(2))
print(m.group(0)) # m 전체를 반환
print(m)

test
gmail.com
test@gmail.com
<_sre.SRE_Match object; span=(0, 14), match='test@gmail.com'>


### 반복의 횟수 제한

In [198]:
print(re.search("pi{4}g","piiiig"))

#원래 i 까지 포함해서 3~4번 반복일때만 반환
#아니면 None을 반환



<_sre.SRE_Match object; span=(0, 6), match='piiiig'>


### minimum 매칭

In [211]:
print(re.search("pi{3,5}g","piiiiig"))
re.search(r"<.+>","<html>haha</html>")
re.search(r"<.+?>","<html>haha</html>")
print(re.search(r"eeefdf[d*e]","eeefdf*ddeeeee"))

re.search(r"a{3,5}","aaaaa")
re.search(r"a{3,5}?","aaaaa")

<_sre.SRE_Match object; span=(0, 7), match='piiiiig'>
<_sre.SRE_Match object; span=(0, 7), match='eeefdf*'>


<_sre.SRE_Match object; span=(0, 3), match='aaa'>

### match 는 search 의 ^와 동일  

search는 그냥 그 문자열에 어디에나 있으면 되는데 match는 무조건 맨앞에서 부터 찾음  
^와 동일!

In [ ]:
re.match(r"\d\d\d","my number is 123)
re.match(r"\d\d\d","123 is my number")
re.search(r"^\d\d\d", "123 is my number")

search => 최초로 매칭되는 패턴만 반환

findall => 매칭되는 모든 패턴 반환

In [73]:
print(re.search(r"[\w-]+@[\w.]+","test@gmail.com hahaa test2@gmail.comnice test test"))
print(re.findall(r"\w+@[\w.]+", "test@gmail.com haha test2@gmail.com nice test test"))

<_sre.SRE_Match object; span=(0, 14), match='test@gmail.com'>
['test@gmail.com', 'test2@gmail.com']


In [71]:
print(re.search(r"abc","abc abc abc"))
print(re.findall(r"abc","abc abc abc"))

<_sre.SRE_Match object; span=(0, 3), match='abc'>
['abc', 'abc', 'abc']


In [49]:
print(m.start())
print(m.end()) #= > [m.start:m.end()] 했을 때 전체열이 다 반환될 숫자를 반환해줌.
# 즉 실제 index 끝 값 +1 해준 값을 반환함
print(m)

0
14
<_sre.SRE_Match object; span=(0, 14), match='test@gmail.com'>


### sub  
주어진 문자열에서 일치하는 모든 패턴을 replace  
그 결과를 문자열로 다시 반환  
두번재 인자는 특정 문자열이 될 수도, 함수가 될 수도 있음  
count 가 0인 경우는 전체를, 1이상이면 해당 숫자만큼 치환

In [77]:
re.sub(r"[\w-]+@[\w.]+","great","test@gmail.com haha rulrul test2@gmail.com", count=1)
re.sub(r"[\w-]+@[\w.]+","great","test@gmail.com haha rulrul test2@gmail.com", count=0)
re.sub(r"[\w-]+@[\w.]+","great","test@gmail.com haha rulrul test2@gmail.com", count=2)
re.sub(r"[\w-]+@[\w.]+","great","test@gmail.com haha rulrul test2@gmail.com", count=3)

'great haha rulrul great'

### compile  
동일한 정규표현식을 매번 다시 쓰기 번거로움을 해결  
compile로 해당 표현식을 re.Regexobject 객체로 저장하여 사용 가능

In [78]:
email_reg = re.compile(r"[\w-]+@[\w.]+")
email_reg.search("test@gail.com haha test2.gmail.com")

<_sre.SRE_Match object; span=(0, 13), match='test@gail.com'>

# Numpy

In [79]:
import numpy as np

In [89]:
x=np.array([0,1,2])
print(x)
print(type(x))

x=np.eye(3)
print(x)

x=np.linspace(1,10,3)
print(x)

x=np.arange(1,16)
print(x)
print(x.shape)
print(x.reshape((3,5)))
print(x)

print(np.random.rand(2,3)) #0과 1사이의 2행 3열의 형태로 array 생성
print(np.random.randn(2,3)) #정규분포로 샘플링 된 랜덤 ndarray 생성


np.random.seed(5)
np.random.rand(3,2) # 이때 seed를 다시 실행하면 같은 랜덤 값이 순차적으로 반환

#uniform 과 normal 은 범위를 줄 수도 안줄 수도 있음.
print(np.random.uniform(size=(2,3)))
print(np.random.normal(1,5,size=(2,3)))

print(np.random.randint(1,11, size=(5,1))) #1에서 11 미만  정수 사이에 랜덤 샘플링

[0 1 2]
<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1.   5.5 10. ]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[0.62878791 0.57983781 0.5999292 ]
 [0.26581912 0.28468588 0.25358821]]
[[-0.87187918 -0.42250793  0.99643983]
 [ 0.71242127  0.05914424 -0.36331088]]
[[4]
 [2]
 [8]
 [4]
 [2]]
[[0.76590786 0.51841799 0.2968005 ]
 [0.18772123 0.08074127 0.7384403 ]]
[[-4.96382306 -0.02438255 -0.79414474]
 [ 4.01735801 -7.32394265 -2.50089519]]


In [208]:
x= np.arange(10).reshape(2,-1)

print(x[1,-1])

x=np.arange(24).reshape(2,-1,4)
print(x)
print(x[1])
print(x[1,1])

# reshape 할 때 하나만 남기고(-1) 써도 알아서 반환해줌
# 그 하나는 -1이라고 써놓으면 됨, 처음 인자이든 중간 인자이든 마지막 인자이든 상관 없음!!!

9
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[16 17 18 19]


In [92]:
print(x.flatten()) #행을 기준으로 펼쳐줌
print(x.flatten(order="F")) #열을 기준으로 펼쳐줌
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0 12  4 16  8 20  1 13  5 17  9 21  2 14  6 18 10 22  3 15  7 19 11 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [96]:
x.ravel()
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [202]:
x=np.random.randint(0,12,size=(2,6))
print(x)

[[ 0  7  7  6 11  0]
 [ 0  8 10  5 11  5]]


In [107]:
print(x.sum()) # 전체 sum 값
print(x.sum(axis=1)) # 열 기준 sum 값
print(x.sum(axis=0)) # 행 기준 sum 값
print(np.sum(x))

57
[33 24]
[10 18  6 14  4  5]
57


In [117]:
z=np.random.randint(1,10,5)
print(z)
print(np.where(z>5,z, 0))


In [150]:
print(x)
print(x[1])

[[ 4  9  3 11  2  4]
 [ 6  9  3  3  2  1]]
[6 9 3 3 2 1]


## 브로드 캐스팅  
뒤에서 부터 비교하여 크기가 같거나 1인 것이 존재하면 연산 가능

## Pandas

In [123]:
import pandas as pd
dic_data={"a":1,"b":2,"c":3}
print(pd.Series(dic_data))
list_data=[1,2,3,4]
print(pd.Series(list_data))

print(pd.Series(dic_data).index)
print(pd.Series(dic_data).values)

a    1
b    2
c    3
dtype: int64
0    1
1    2
2    3
3    4
dtype: int64
Index(['a', 'b', 'c'], dtype='object')
[1 2 3]


In [126]:
tup_data = tuple("abcde")
a = pd.Series(tup_data,index=list("ABCDE"))
print(a)

print(a[0])
print(a["A"])
print(a[1:2])
print(a["A":"B"])
print(a["A":"B"]) # index 글자를 이용한 슬라이싱은 뒷 index 도 포함

A    a
B    b
C    c
D    d
E    e
dtype: object
a
a
B    b
dtype: object
A    a
B    b
dtype: object
A    a
B    b
dtype: object


In [130]:
dic_data={"A":list("aaa"),"B":list("bbb")}
print(pd.DataFrame(dic_data))
df = pd.DataFrame([[1,2,3],[4,5,6]],index=list("AB"),columns=list("abc"))
print(df)
df.rename(columns={"b":"하하","a":"히히"},inplace=True) # 일부만 변경 가능
df.rename(index={"A":"케케"}) # 디폴트 inplace = False
print(df)

   A  B
0  a  b
1  a  b
2  a  b
   a  b  c
A  1  2  3
B  4  5  6
   히히  하하  c
A   1   2  3
B   4   5  6


In [165]:
df.index=["학생1","학생2"]
df.columns=["연령","남녀","소속"] # 일부만 변경 불가능, 알아서 바꿔줌
print(df)
new_index=["학생1","학생2","학생3"]
print(df.reindex(new_index)) # 추가된 인덱스는 NAN 값으로 채워짐 #fill_value =5 로 Nan 값 채우는 것 가틍
print(df)
df2=df.reindex(new_index)

     연령  남녀  소속
학생1   1   2   3
학생2   4   5   6
      연령   남녀   소속
학생1  1.0  2.0  3.0
학생2  4.0  5.0  6.0
학생3  NaN  NaN  NaN
     연령  남녀  소속
학생1   1   2   3
학생2   4   5   6


In [140]:
df.drop(["학생1"], axis=0) #inplace = False 가 디폴트
print(df.drop("학생1"))
print(df.drop("연령",axis=1))
print(df[["연령","남녀"]])

     연령  남녀  소속
학생2   4   5   6
     남녀  소속
학생1   2   3
학생2   5   6
     연령  남녀
학생1   1   2
학생2   4   5


In [146]:
print(df.loc["학생1":"학생2"])
print(df.iloc[1:3])
print(df.loc["학생1":"학생2",["연령","남녀"]])
print(df.iloc[0:2,0:2])

     연령  남녀  소속
학생1   1   2   3
학생2   4   5   6
     연령  남녀  소속
학생2   4   5   6
     연령  남녀
학생1   1   2
학생2   4   5
     연령  남녀
학생1   1   2
학생2   4   5


In [153]:
print(df.T)

    학생1  학생2
연령    1    4
남녀    2    5
소속    3    6


In [177]:
df2=df.set_index("이름")

KeyError: '이름'

In [166]:
print(df)

      연령   남녀   소속
학생1  1.0  2.0  3.0
학생2  4.0  5.0  6.0
학생3  NaN  NaN  NaN


In [171]:
df=df.fillna(3)

In [176]:
print(df.reset_index()) # index를 value 값으로 초기화
print(df.sort_index(ascending=False)) # 행의 index 기준으로 데이터 프레임 정렬
print(df.sort_index(ascending=True, by=["연령","남녀"])) # 동일한 값이 있으면 남녀 큰 순으로


  index   연령   남녀   소속
0   학생1  1.0  2.0  3.0
1   학생2  4.0  5.0  6.0
2   학생3  3.0  3.0  3.0
      연령   남녀   소속
학생3  3.0  3.0  3.0
학생2  4.0  5.0  6.0
학생1  1.0  2.0  3.0
      연령   남녀   소속
학생1  1.0  2.0  3.0
학생3  3.0  3.0  3.0
학생2  4.0  5.0  6.0


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
df.sum(df2, fill_value=0) # NaN 인 값은 즉 하나엔 있는데 하나엔 없는 값, NaN 인 값은 fill_value 로 채워주고 계산해 줄 수가 있음
# Series 와 DataFrame 모두 마찬가지!!

In [212]:
a=pd.Series([1,2,3])
b=pd.Series([1,np.nan,2,5])