## 문제1_데이터 전처리
insta.txt 데이터는 corona를 태그로한 약 instagram 게시글을 크롤링한 데이터 입니다. 해당 데이터를 이용하여 인스타그램 태그를 이용한 분석을 하고 싶습니다. 이를 위한 데이터 전처리 함수를 만들고 전처리를 진행하여 주세요.
1. 데이터를 불러온 후, 하나의 문자열로 읽어오세요  
2. 빈칸을 채워주세요
    - 빈칸1 : 해당 텍스트 안에는 게시글이 POST+숫자(ex: POST94)로 구분되어 있습니다. 이를 기준으로 각 게시글을 분리할 수 있도록 빈칸에 정규표현식을 작성하세요
    - 빈칸2 : 추출한 게시글에서 태그만을 추출할 수 있도록 빈칸에 정규표현식을 작성하세요
        - #을 포함하여 추출하세요
        - #뒤의 영숫자 개수가 2개 이상인 것만 추출할 수 있게 작성하세요
        - ex) "\s"
    - 빈칸3: RegexpTokenizer클래스의 tokenize 함수를 이용하여 문장을 구분하세요
        - tokenize 함수 : 텍스트를 인자로 받아서 해당 분류기를 이용하여 텍스트를 분류, 이를 각 리스트 원소로 한 리스트 반환
        - ex) RegxpTokenizer(정규표현식).tokenize(text)
    - 빈칸4: RegexpTokenizer클래스의 tokenize를 이용하여 각 문장에서 단어를 추출하세요.
    - 빈칸5 : words 리스트 안의 각 단어에서 "#"을 제거한 후 모두 소문자로 변경하고 개별 단어가 스톱워드의 단어에 포함되지 않으면 filtered_words 리스트에 추가하세요.
    - 빈칸6 : 해당 리스트 안에서의 중복된 단어를 제거하세요.  
1. 함수를 실행하세요

In [1]:
import numpy as np
import nltk
nltk.download("stopwords") # 언어별 스톱 워드를 제공
stopwords = nltk.corpus.stopwords.words("english")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\이혜림\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
data = open("./프로젝트/insta.txt").read()

In [3]:
# 인스타그램 게시글에서 태그만을 추출하는 함수
def tags_extraction(data):
    import re 
    from nltk.tokenize import RegexpTokenizer # 정규표현식을 사용할 수 있는 토큰화함수
    
    words = [] # 단어 토큰을 저장할 list
    filtered_words = [] # 필터화된 단어 토큰을 저장할 list
    
    """
    RegexpTokenizer(정규표현식, gaps=False)
    gaps=True이면 해당 정규표현식을 기준으로 분류
    gaps=False이면 해당 정규표현식만을 추출
    """
    tokenizer_sentence = RegexpTokenizer("POST\d", gaps=True) # 문장 토큰 분류기
    tokenizer_word=RegexpTokenizer("#\w\w+") # 단어 토큰 분류기
    
    sentences = tokenizer_sentence.tokenize(data)
        
    for sentence in sentences:
        words += tokenizer_word.tokenize(sentence)
   
    # words 리스트 안의 단어를 "#"을 제거한 후 모두 소문자로 변경하고 개별 단어가 스톱 워드의 단어에 포함되지 않으면 filter_words에 추가
    for idx, w in enumerate(words):
        w = w[1:].lower() # # 제거 및 소문자로 변경
        if w not in stopwords:
            filtered_words.append(w)
    
    # words 리스트 안의 단어의 중복을 제거하세요
    return list(set(filtered_words))

In [6]:
tags_extraction(data) # 실행하세요

# 문제3_CountVectorizer
- disney_plus_shows.csv 데이터는 디즈니+스트림 서비스에서 이용할 수 있는 쇼에 대한 정보입니다. 데이터를 사용하여 밑의 문제를 풀어주세요 !

In [3]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

- 데이터의 모든 결측치를 제거하여 주세요.(행 기준)

In [4]:
# 데이터 불러오기
d_show = pd.read_csv('disney_plus_shows.csv', index_col=0)[:5]

In [5]:
# 결측치 제거
d_show.dropna(how='any', inplace=True)
print(d_show.isnull().sum())

title          0
plot           0
type           0
rated          0
year           0
released_at    0
added_at       0
runtime        0
genre          0
director       0
writer         0
actors         0
language       0
country        0
awards         0
metascore      0
imdb_rating    0
imdb_votes     0
dtype: int64


- CountVectorizer() 메소드를 이용하여 count_vec 객체를 만들어주세요.
- 파리미터 옵션
    + stop_words="english"
    + analyzer='word', 
    + ngram_range=(1, 2)
    + min_df=1
    + max_features=None
- 생성된 객체에 d_show데이터의 plot 변수를 넣어주세요.

In [6]:
# 객체 생성
count_vec = CountVectorizer(stop_words="english", analyzer='word', 
                            ngram_range=(1, 2),  min_df=1, max_features=None)
# plot 변수 fitting
count_vec.fit(d_show['plot'])

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

- get_feature_names()를 사용해 데이터의 단어들을 5칸 간격 차이로 출력해 주세요.
- vocabulary_를 사용해 단어들이 각각 몇번씩 쓰였는지 출력해주세요.

In [7]:
# get_feature_names() 사용
print("\n<Every 5rd feature>\n{}".format(count_vec.get_feature_names()))
# vocabulary_ 사용
count_vec.vocabulary_


<Every 5rd feature>
['coat', 'coat instead', 'creates', 'creates extravagant', 'cruella', 'cruella devil', 'dalmatian', 'dalmatian puppies', 'date', 'date ill', 'designer', 'designer plots', 'devil', 'devil gets', 'does', 'evil', 'evil high', 'extravagant', 'extravagant fur', 'extravagant mess', 'fashion', 'fashion designer', 'fur', 'fur coat', 'gets', 'gets prison', 'goes', 'goes puppies', 'high', 'high fashion', 'ill', 'ill tempered', 'instead', 'instead creates', 'make', 'make extravagant', 'mess', 'older', 'older sister', 'order', 'order make', 'plots', 'plots steal', 'popular', 'popular teenager', 'pretty', 'pretty popular', 'prison', 'prison goes', 'puppies', 'puppies order', 'sister', 'sister does', 'steal', 'steal dalmatian', 'teenager', 'teenager date', 'tempered', 'tempered older']


{'pretty': 45,
 'popular': 43,
 'teenager': 55,
 'date': 8,
 'ill': 30,
 'tempered': 57,
 'older': 37,
 'sister': 51,
 'does': 14,
 'pretty popular': 46,
 'popular teenager': 44,
 'teenager date': 56,
 'date ill': 9,
 'ill tempered': 31,
 'tempered older': 58,
 'older sister': 38,
 'sister does': 52,
 'evil': 15,
 'high': 28,
 'fashion': 20,
 'designer': 10,
 'plots': 41,
 'steal': 53,
 'dalmatian': 6,
 'puppies': 49,
 'order': 39,
 'make': 34,
 'extravagant': 17,
 'fur': 22,
 'coat': 0,
 'instead': 32,
 'creates': 2,
 'mess': 36,
 'evil high': 16,
 'high fashion': 29,
 'fashion designer': 21,
 'designer plots': 11,
 'plots steal': 42,
 'steal dalmatian': 54,
 'dalmatian puppies': 7,
 'puppies order': 50,
 'order make': 40,
 'make extravagant': 35,
 'extravagant fur': 18,
 'fur coat': 23,
 'coat instead': 1,
 'instead creates': 33,
 'creates extravagant': 3,
 'extravagant mess': 19,
 'cruella': 4,
 'devil': 12,
 'gets': 24,
 'prison': 47,
 'goes': 26,
 'cruella devil': 5,
 'devil gets'

# 문제4 COO, CSR 적용

In [89]:
from scipy import sparse

In [90]:
matrix_array = np.array([[0,2,3,0,1,4],
                  [3,5,9,0,0,8],
                  [4,3,0,1,2,8],
                  [2,0,9,9,1,0],
                  [0,0,2,0,9,1],
                  [8,2,0,3,0,0]])

- 0이 아닌 데이터 추출
- 행 위치와 열 위치를 각각 array로 생성
- 행 위치 배열의 고유한 값의 시작 위치 인덱스를 배열로 생성

In [95]:
# 0이 아닌 데이터 추출
data = np.array([2,3,1,4,3,5,9,8,4,3,1,2,8,2,9,9,1,2,9,2,8,2,3])

# 행 위치
row_pos = np.array([0,0,0,0,1,1,1,1,2,2,2,2,2,3,3,3,3,4,4,4,5,5,5])
# 열 위치
col_pos = np.array([1,2,4,5,0,1,2,5,0,1,3,4,5,0,2,3,4,2,4,5,0,1,3])
# 고유한 인덱스 배열
row_pos_ind = np.array([0,4,8,13,17,20,23])

- COO 형식으로 변환
- CSR 형식으로 변환
- toarray()를 통해 출력 확인

In [100]:
# COO 형식으로 변환
sparse_coo = sparse.coo_matrix((data, (row_pos,col_pos)))
# CSR 형식으로 변환
sparse_csr = sparse.csr_matrix((data,col_pos,row_pos_ind))
print(sparse_coo.toarray())
print()
print(sparse_csr.toarray())

[[0 2 3 0 1 4]
 [3 5 9 0 0 8]
 [4 3 0 1 2 8]
 [2 0 9 9 1 0]
 [0 0 2 0 9 2]
 [8 2 0 3 0 0]]
[[0 2 3 0 1 4]
 [3 5 9 0 0 8]
 [4 3 0 1 2 8]
 [2 0 9 9 1 0]
 [0 0 2 0 9 2]
 [8 2 0 3 0 0]]
