# week2 - 복습과제

# 문제1
## 정규표현식 활용 문제입니다.
### 주어진 문제를 푸세요.

아래는 인터넷 기사의 본문을 크롤링한 코드입니다.<br/>
크롤링의 코드는 이해하지 않으셔도 됩니다.<br/>
news1의 출력결과만 확인하세요.(참고로 new1의 타입은 str입니다)<br/>
(이런식으로 정규표현식이 쓰인다는 것을 표현한 것이니, 크롤링 코드에 대해 어려움을 겪지 마셔용)

In [1]:
import requests
from bs4 import BeautifulSoup
# 위의 두 모듈이 없는 경우에는 pip install requests bs4 실행

def get_news_content(url):
    response = requests.get(url)
    content = response.text

    soup = BeautifulSoup(content, 'html5lib')

    div = soup.find('div', attrs = {'id' : 'harmonyContainer'})
    
    content = ''
    for paragraph in div.find_all('p'):
        content += paragraph.get_text()
        
    return content

news1 = get_news_content('https://news.v.daum.net/v/20190617073049838')
print(news1)
#print(type(news1))

(로스앤젤레스=연합뉴스) 옥철 특파원 = 팀 쿡 애플 최고경영자(CEO)가 16일(현지시간) 실리콘밸리 앞마당 격인 미국 서부 명문 스탠퍼드대학 학위수여식에서 테크기업들을 향해 쓴소리를 쏟아냈다.쿡은 이날 연설에서 실리콘밸리 테크기업들은 자신들이 만든 혼란에 대한 책임을 질 필요가 있다고 경고했다.근래 IT 업계의 가장 큰 이슈인 개인정보 침해, 사생활 보호 문제를 콕 집어 라이벌인 구글, 페이스북 등 IT 공룡을 겨냥한 발언이라는 해석이 나왔다.쿡은 "최근 실리콘밸리 산업은 고귀한 혁신과는 점점 더 거리가 멀어지는 것으로 알려져 있다. 책임을 받아들이지 않고도 신뢰를 얻을 수 있다는 그런 믿음 말이다"라고 꼬집었다.개인정보 유출 사건으로 미 의회 청문회에 줄줄이 불려 나간 경쟁사 CEO들을 향해 일침을 가한 것으로 보인다.그는 또 실리콘밸리에서 희대의 사기극을 연출한 바이오벤처 스타트업 테라노스(Theranos)를 직격했다.쿡은 "피 한 방울로 거짓된 기적을 만들 수 있다고 믿었느냐"면서 "이런 식으로 혼돈의 공장을 만든다면 그 책임에서 절대 벗어날 수 없다"라고 비난했다.테라노스는 손가락 끝을 찔러 극미량의 혈액 샘플만 있으면 각종 의학정보 분석은 물론 거의 모든 질병 진단이 가능한 바이오헬스 기술을 개발했다고 속여 월가 큰손들로부터 거액의 투자를 유치했다가 해당 기술이 사기인 것으로 드러나 청산한 기업이다.쿡은 애플의 경우 프라이버시(사생활) 보호에 초점을 맞춘 새로운 제품 기능들로 경쟁사들에 맞서고 있다며 자사의 데이터 보호 정책을 은근히 홍보하기도 했다.oakchul@yna.co.kr


### (1)
- 위 출력 값에서 정규표현식을 사용하여 이메일주소( ex) oakchul@yna.co.kr )를 추출하여 str 타입으로 반환하여 출력하세요.
 - 조건 : compile 함수 사용 

출력결과<br/>
```'oakchul@yna.co.kr'```

In [2]:
import re
# 힌트 : re.Match 객체에서 결과를 반환하는 메소드는 .group()입니다.
# 이해가 안된다면 실행해보세요~

# a = re.search(r'^b\w+a', 'babana') 
# print(a)
# print(type(a))
# b = re.search(r'^b\w+a', 'babana').group()
# print(b)
# print(type(b))

In [28]:
import re
email_compile = re.compile(r"[\w-]+@[\w.]+") 
email = email_compile.search(news1)
email = email.group()
print(email)

oakchul@yna.co.kr


### (2)
- 주어진 리스트에서 올바른 (http://, https://) 웹페이지만 찾고, 올바른 웹페이지만 새로운 리스트로 만들어보세요
 - 힌트 : 1. 정규표현식 / 2. 반복문과 조건문
 - 다른 방법을 알고 계신다면 됩니다.( ex) map() 등등)

출력결과<br/>
``['http://www.test.co.kr',
 'https://www.test1.com',
 'http://www.test.com',
 'http://www.google.com']``

In [53]:
webs = ['http://www.test.co.kr', 
        'https://www.test1.com', 
        'http://www.test.com', 
        'ftp://www.test.com', 
        'http:://www.test.com',
       'htp://www.test.com',
       'http://www.google.com', 
       'https://www.homepage.com.']

In [93]:
correct_webs=[]
correct_webs = [i.group() for i in map(lambda x: re.search("https?://[\w.]+" , x,), webs) if i ]
print(correct_webs)

['http://www.test.co.kr', 'https://www.test1.com', 'http://www.test.com', 'http://www.google.com', 'https://www.homepage.com.']


# 문제 2 - numpy 모듈 활용하기

### (1) 3주치 로또번호 ( 1~45사이의 값 ) , 총 18개의 번호를 numpy 의 random 서브모듈을 통해 array 에 저장해주요. ( 중복가능) 

In [89]:
import numpy as np
lotto = np.random.randint(1,46, 18)
print(lotto)

[ 5 28 38 40 29 27 39 28 11 42  9  6 14 20 36 40 43  1]


### (2) 문제 2-(1) 에서 생성한 list를 numpy모듈의 함수를 통해 을 통해 3행 6열로 이루어진 행렬로 만들어주세요.

In [90]:
lotto = lotto.reshape(3,6)
print(lotto)

[[ 5 28 38 40 29 27]
 [39 28 11 42  9  6]
 [14 20 36 40 43  1]]


### (3)  문제 2-(2)에서 만든 행렬을 열기준으로 flatten 해주세요 .


In [91]:
lotto = lotto.flatten(order = "F")
print(lotto)

[ 5 39 14 28 28 20 38 11 36 40 42 40 29  9 43 27  6  1]


# 문제3

## 다음표와 같은 데이터 프레임을 만들어 보세요.( 편한 방법으로 !) 
### * 만든 데이터 프레임은 문제 3~5 에서 쓰이기 때문에 변수에 저장해주세요! 
       

이름|성별|age|거주지
-|-|-|-
하하하|남|40|울산
히히히|여|20|대전
호호호|남|30|인천

In [106]:
import pandas as pd

In [128]:
data = pd.DataFrame({"이름":"하하하 히히히 호호호".split(),"성별":["남","여","남"], "age": [40,20,30],
                      "거주지":"울산 대전 인천".split()})

In [129]:
print(data)

    이름 성별  age 거주지
0  하하하  남   40  울산
1  히히히  여   20  대전
2  호호호  남   30  인천


# 문제4


### (1) 문제 3에서 만든 데이터 프레임의 'age'열의 이름을 '나이'로 변경해주세요.

In [130]:
data.rename(columns = {"age":"나이"}, inplace =True)
data

이름 성별  나이 거주지
0  하하하  남  40  울산
1  히히히  여  20  대전
2  호호호  남  30  인천

### (2) 문제3에서 만든 데이터프레임의 '이름' 열은 행 인덱스로 지정해주세요


In [131]:
data.index = data["이름"]
data

이름 성별  나이 거주지
이름                 
하하하  하하하  남  40  울산
히히히  히히히  여  20  대전
호호호  호호호  남  30  인천

In [132]:
del data["이름"]
data

성별  나이 거주지
이름            
하하하  남  40  울산
히히히  여  20  대전
호호호  남  30  인천

# 문제5


### (1) 데이터 프레임 '나이'열에 random 한 정수를 더해주세요 ( 시리즈 vs 숫자 ppt 참고! )

In [133]:
import random
data["나이"] += random.randint(-100,100)

In [134]:
data

성별  나이 거주지
이름            
하하하  남   5  울산
히히히  여 -15  대전
호호호  남  -5  인천

### (2) 변경된 '나이'열 기준으로 데이터 프레임을 정렬해주세요.

In [136]:
data = data.sort_index(by="나이")
print(data)

    성별  나이 거주지
이름            
히히히  여 -15  대전
호호호  남  -5  인천
하하하  남   5  울산


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  """Entry point for launching an IPython kernel.
